-- CreateTable
CREATE TABLE "DuesRate" (
    "id" TEXT NOT NULL,
    "activityId" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "effectiveFrom" INTEGER NOT NULL,
    "setById" TEXT,
    "setAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DuesRate_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "DuesRate_activityId_effectiveFrom_key" ON "DuesRate"("activityId", "effectiveFrom");

-- AddForeignKey
ALTER TABLE "DuesRate" ADD CONSTRAINT "DuesRate_activityId_fkey" FOREIGN KEY ("activityId") REFERENCES "Activity"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DuesRate" ADD CONSTRAINT "DuesRate_setById_fkey" FOREIGN KEY ("setById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Seed one beginning-of-time Dues Rate per existing Activity, in the same
-- migration that creates the table, so there is never a moment in which an
-- Activity has no rate and a Billing Period fails to resolve.
--
-- One row in, one row out. The SELECT reads "Activity" alone -- no join, no
-- filter, no aggregate -- and "Activity"."id" is that table's primary key, so
-- every Activity produces exactly one row and no Activity produces two. The
-- unique index created above cannot be violated: this migration created the
-- table empty and writes (activityId, 0) once per Activity. Zero Activities
-- inserts zero rows and succeeds, which is what a fresh database does.
--
-- No other table is written. This migration names "Payment", "Attendance",
-- "Membership" and "ActivitySession" nowhere, and reads "Activity" and "User"
-- only through the foreign keys above, so every existing row of every other
-- table is left exactly as it was.
--
-- "setById" is left NULL deliberately: this amount is the Activity's standing
-- price carried forward, not an Admin's decision taken now, and naming somebody
-- would invent a decision nobody made. "setAt" takes the column default, which
-- is the moment this row actually came into existence.
--
-- The id is a uuid rather than a cuid because cuid() is generated by the Prisma
-- client and there is no client running here. Nothing in the application parses
-- an id. gen_random_uuid() is built into PostgreSQL 13 and later.
INSERT INTO "DuesRate" ("id", "activityId", "amount", "effectiveFrom")
SELECT gen_random_uuid()::text, "id", "monthlyFee", 0
FROM "Activity";
